create table usuario(
    IDUSUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    LOGIN VARCHAR(45),
    SENHA VARCHAR(45),
    TOKEN VARCHAR(45),
    VALIDATOR VARCHAR(6),
    STATUS VARCHAR(1),
    DATAHORAINC TIMESTAMP,
    DATAHORAALT TIMESTAMP,
    DATAHORADEL TIMESTAMP
)