create table produto_comparado(
    IDPRODUTOCOMPARADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDUSUARIO INT,
    IDCOMPARACAO INT,
    IDPRODUTO INT,
    DATAHORAINC TIMESTAMP,
    DATAHORAALT TIMESTAMP,
    DATAHORADEL TIMESTAMP
);


create table produto(
    IDPRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    CODBARRA VARCHAR(100),
    DATAHORAINC TIMESTAMP,
    DATAHORAALT TIMESTAMP,
    DATAHORADEL TIMESTAMP
);

create table comparacao(
    IDCOMPARACAO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DATAHORAINC TIMESTAMP,
    DATAHORAALT TIMESTAMP,
    DATAHORADEL TIMESTAMP
);

create table produto_pesquisado(
    IDPRODUTOPESQUISADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDPRODUTO INT,
    DATAHORAINC TIMESTAMP,
    DATAHORAALT TIMESTAMP,
    DATAHORADEL TIMESTAMP
);